### ISSUE TITLE
Failing automated test in tester plugin with BD 1.1 b5 installer

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-milstd2525-plugin#8]
Win7/10

```
Test name: MIL-STD-2525-Test that renderer correctly saved in the project
Test result:Test failed at step 'Run unit test' with message:
(<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'type'",), <traceback object at 0x00000000295B0148>)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\unittest\case.py", line 331, in run
    testMethod()
  File "C:/Users/boundless/.qgis2/python/plugins\milstd2525\tests\testerplugin.py", line 188, in testRendererSavedToProject
    self.assertEquals("MilStd2525Renderer", layerRenderer.type())

Traceback (most recent call last):
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\testerwidget.py", line 119, in runNextStep
    execute(step.function)
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\utils.py", line 70, in execute
    return func()
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\test.py", line 66, in _runTest
    raise Exception(desc)
Exception: (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'type'",), <traceback object at 0x00000000295B0148>)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\unittest\case.py", line 331, in run
    testMethod()
  File "C:/Users/boundless/.qgis2/python/plugins\milstd2525\tests\testerplugin.py", line 188, in testRendererSavedToProject
    self.assertEquals("MilStd2525Renderer", layerRenderer.type())
```

**Comment by alexbruy** [comment]
Should be fixed
